- hosts: localhost
  vars:
    version: "{{ lookup('file', 'version.txt') }}"
  tasks:
  - name: Creacion de index con Jinja2
    template:
      src: index.j2
      dest: index.html
  - name: Configurar s3 bucket con index
    amazon.aws.aws_s3:
      bucket: mapfre-gitops-amelgar
      object: index.html
      src: index.html
      permission: public-read
      mode: put
  #- name: Ejecuta un ls
    #ansible.builtin.shell: 
    # cmd: ls -la
    #  chdir: ./
  - name: Ejecuta el CHANGELOG
    ansible.builtin.script: ./cambios.sh > CHANGELOG.md
  - name: Ejecuta el versionado
    ansible.builtin.shell:
      cmd: ./version.sh > version.txt